version: "3"
services:
  compose-node-app:
    # build: ./Dockerfile.dev
    build: 
      context: .
      target: development
    volumes:
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=development
    command: npm run dev
